### ISSUE TITLE
LFW RGB Image vs Gray Scale Image

### ISSUE THREAD

**Issue by FeiMiBa** [siriusdemon/Build-Your-Own-Face-Model#11]
博主你好，你24.pth那个模型在LFW灰度图上测的Acc在0.96+，请问你有在RGB图上的模型吗，效果差别大不大？

**Comment by siriusdemon** [comment]
差别不大的。还有就是，如果你要实用，建议换个更大的数据集来训练，webface还是太小了。

**Comment by FeiMiBa** [comment]
@siriusdemon 感谢提供的教程和信息，手动点赞👍
