### ISSUE TITLE
Face detector bounding box issue

### ISSUE THREAD

**Issue by chujianfeng** [siriusdemon/Build-Your-Own-Face-Model#14]
我學習了您的代碼，
但我發現使用在視頻偵測人臉時，
Bounding box 會有蠻明顯的抖動 or 縮放。
我懷疑是 Heatmap 的問題，不知道作者有什麼看法呢?

若要改善這個問題有什麼好辦法嗎?!

**Comment by siriusdemon** [comment]
如果您想在生产环境下使用，推荐用 dbface 的模型。这个只是个简化的教程。

**Comment by chujianfeng** [comment]
好的，謝謝您!
您的代碼讓我受益良多
