### ISSUE TITLE
训练自己的（大）数据集

### ISSUE THREAD

**Issue by MOKEjf** [siriusdemon/Build-Your-Own-Face-Model#16]
博主你好，我想问问我是用的我自己的数据集训练的，模型的损失在8 左右就无法再收敛了，在你给的lfw上面做的测试，测试的acc在80%，你看这个问题是正常的吗？？望回复，感谢

**Comment by siriusdemon** [comment]
正常吧应该【笑哭】
你的数据集有多大？如果数据集很大，考虑是欠拟合问题，用 resnet 版的，不要用 mobilenet 版的。你给的信息太少不知道怎么回你【笑哭】

**Comment by MOKEjf** [comment]
数据集确实挺大的，用的是celeba数据集，然后我应该是没有改动你上面说的这两个版本的。

**Comment by siriusdemon** [comment]
你试过 resnet 版的，也是很低吗？可以训练久一点试试。

**Comment by MOKEjf** [comment]
resReset版本我没用，我还在研究怎么改，有点菜。



---原始邮件---
发件人: "Sirius Demon"<notifications@github.com&gt;
发送时间: 2020年11月20日(周五) 下午2:15
收件人: "siriusdemon/Build-Your-Own-Face-Model"<Build-Your-Own-Face-Model@noreply.github.com&gt;;
抄送: "MOKEjf"<1134872410@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [siriusdemon/Build-Your-Own-Face-Model] 模型收敛的损失在8左右正常吗？ (#16)




 
你试过 resnet 版的，也是很低吗？可以训练久一点试试。

**Comment by MOKEjf** [comment]
> 你试过 resnet 版的，也是很低吗？可以训练久一点试试。

我训练的比较久，但是效果一样，我接下来实施你说的这个版本

**Comment by MOKEjf** [comment]
我现在改了，明天应该会有结果，我训练好了给你反馈吧，感谢博主

**Comment by MOKEjf** [comment]
博主，我重新训练了，换的resnet，现在的准确率挺高的，模型也收敛到3左右

**Comment by LuoKaiGSW** [comment]
> 博主，我重新训练了，换的resnet，现在的准确率挺高的，模型也收敛到3左右
你好，我最近也在复现centerface，请问这个resnet版本的应该如何修改？

**Comment by Shame-fight** [comment]
> 博主，我重新训练了，换的resnet，现在的准确率挺高的，模型也收敛到3左右

您好，请问如何获得resnet版本需要的资料（网络模型等）

**Comment by piginzoo** [comment]
我的也是不收敛，用的是CeleBa数据集，1万个分类，请教m和s超参多少啊？我看了您的代码，用的还是默认的m=0.5和s=30，不过我看了原始论文，他推荐是m=1.35，大概是77度。另外，论文里没有推荐半径s的值。这2个超参您在训练过程中，如何把握的呢？请教 ：https://github.com/piginzoo/arcface-pytorch.git

**Comment by aizsa2022** [comment]
mobilenet用了博主指定的数据集：CASIA-WebFace-Clean训练，lfw-align-128为测试，，，训练50轮，在5-6轮后， loss后面都在10-5-10之间跳，但是ACC稳定在0.96*上下，，，用resnet训练了几轮了，没一点收敛的迹象。这样正常吗？哪里设置有问题呢？

![1loss-MBnet-ArcFace-WebFace-Clean png](https://user-images.githubusercontent.com/112769693/191041555-fcc6832c-46d5-4f82-9016-553172071770.png)
![1Acc-MBnet-ArcFace-WebFace-Clean](https://user-images.githubusercontent.com/112769693/191041650-c03ec3aa-bbf5-4a5f-b45e-02fdf27b90bf.png)
