### ISSUE TITLE
人脸检测 特征点heatmap是否有错？

### ISSUE THREAD

**Issue by geoffzhang** [siriusdemon/Build-Your-Own-Face-Model#17]
lm_xs = (lm_xs - bbox[0]) / original_width
lm_ys = (lm_ys - bbox[1]) / original_height

论文中应该是剪去bbox的中心坐标？这里是否有误

**Comment by siriusdemon** [comment]
这是有意为之。我博客中应该有说明。你按论文的做也可以，后处理对应改下就好。人脸检测也推荐你看看 dbface ，他们做的更好。
