### ISSUE TITLE
对阈值有一些疑惑？

### ISSUE THREAD

**Issue by bigcash** [siriusdemon/Build-Your-Own-Face-Model#2]
首先感谢作者，写的很好！
我在看第6章的第7小节中，作者有这么一句话：“用选好的阈值进行划分，大于此阈值的是不同人的脸，小于此阈值的是同一个人的脸”。感觉是不是写反了，大于此阈值的是相同的脸。
理由：代码段“y_test = (y_score >= th)”，分值大于阈值的为1，否则为0，而对应的label：y_true的值，也是1对应的同一张脸，0是不同的脸。

**Comment by siriusdemon** [comment]
你是对的，谢谢！
