### ISSUE TITLE
fmobile训练一个epoch要多久

### ISSUE THREAD

**Issue by guovxu** [siriusdemon/Build-Your-Own-Face-Model#21]
请问用fmobile模型训练网络，数据集为CASIA, 一个epoch要多长时间？

**Comment by siriusdemon** [comment]
你自己试一下啊

**Comment by guovxu** [comment]
额，是我没说清楚。我尝试了，大概要两个小时，但是同组的同学用别的模型同样的数据集一个epoch只要十来分钟，所以想问下两个小时正常吗

**Comment by siriusdemon** [comment]
嗯，不用那么久。是不是没用 GPU？
