### ISSUE TITLE
train问题

### ISSUE THREAD

**Issue by GoPikachue** [siriusdemon/Build-Your-Own-Face-Model#28]
我训练的时候，模型的Network Setup占用大量的时间，并且执行到第一个epoch的第一个batch的时候就一直在执行，即没有执行到下一个batch也没有报错。想请教一下可能的原因。

**Comment by siriusdemon** [comment]
也许是图片加载太慢了。你可以用小的 batch 下试试。比如 batch=2 ?

**Comment by GoPikachue** [comment]
谢谢你的回复！
    我检查了一下，发现存在的问题是模型加载过程非常慢。我的GPU是3070，cuda版本是10.0。我查阅资料后找到了原因，30系列显卡是新一代架构，新驱动不支持cuda9以及cuda10，所以必须安装cuda11。我改为cuda11之后，模型可以正常加载和使用了。再次感谢！！！
