### ISSUE TITLE
accuracy与threshold的关系？

### ISSUE THREAD

**Issue by Linsongrong** [siriusdemon/Build-Your-Own-Face-Model#8]

**Comment by Linsongrong** [comment]
这里两者的关系都是越大越好吗？作者您训练好的模型测试，这里个值差值大吗？

**Comment by siriusdemon** [comment]
模型只会输出人脸的特征，但模型本身没有这两个人脸是不是同一个人这样的概念。这是由开发者采用的距离度量或者相似度函数决定的。常见的有欧几里得距离、余弦相似度。
以余弦相似度来说，它是一个`-1, 1` 之间的数。
那么，两个人脸的相似度有多少，就认为这是同一个人呢？这个划分两个人脸是否为同一个人的数值，就叫做 threshold。
accuracy 当然是越大越好。

**Comment by learncsxiao** [comment]
你好，训练了你的模型，但是loss只能降到5左右，而且有点震荡，可以请教一下你是怎么把loss降到1，把精度提上去的呢

**Comment by siriusdemon** [comment]
换另一个模型呀。里面有一个resnet的。
