### ISSUE TITLE
训练时间

### ISSUE THREAD

**Issue by soolone** [siriusdemon/Build-Your-Own-Face-Model#9]
请问下大概多少个epoch loss能够降到1呢？现在batch_size 128，训练了大概300个epoch维持在5左右降不下去

**Comment by siriusdemon** [comment]
这说明模型只能收敛到当前的水平，您可以换个模型试试。我做实验的时候，用`fmobilenet`只能收敛到4～6，用`resnet`能收敛到1左右。

**Comment by soolone** [comment]
好的，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siriusdemon/Build-Your-Own-Face-Model"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 下午3:02
收件人:&nbsp;"siriusdemon/Build-Your-Own-Face-Model"<Build-Your-Own-Face-Model@noreply.github.com&gt;;
抄送:&nbsp;"sjc"<980756075@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [siriusdemon/Build-Your-Own-Face-Model] 训练时间 (#9)





 
这说明模型只能收敛到当前的水平，您可以换个模型试试。我做实验的时候，用fmobilenet只能收敛到4～6，用resnet能收敛到1左右。
